FROM ubuntu:18.04
RUN apt-get update && apt-get install -y curl openjdk-8-jre
WORKDIR /opt/app
# TODO part of build? maybe in CI?
COPY files/app.jar .
COPY files/docker-entrypoint.sh files/wait-for-it.sh  /
ENTRYPOINT ["/docker-entrypoint.sh"]
